name: Docker Image CI

on:
  push:
    branches: [ "CI" ]
  pull_request:
    branches: [ "CI" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - name: Build & push Docker image
        run: docker --version | docker build -t simple-nodeci . | docker tag simple-node davidermias/simple-nodeci
        # username: ${{ secrets.DOCKER_USER_NAME }}
        # password: ${{ secrets.DOCKER_USER_PASS }}
