name: Docker Image CI

on:
  push:
    branches: [ "CI" ]
  pull_request:
    branches: [ "CI" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Check out code
      
      - name: List Docker image         
        run: docker --version | docker images
      - name: Tag to Push to Dockerhub 
        run: tag simple-nodeci davidermias/simple-nodeci 
      - name: Build Docker Image
        run: docker build -t simple-nodeci .
        # username: ${{ secrets.DOCKER_USER_NAME }}
        # password: ${{ secrets.DOCKER_USER_PASS }}
