name: Docker Image CI

on:
  push:
    branches: [ "CI" ]
  pull_request:
    branches: [ "CI" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: davidermias/simple-nodeci:latest
          tags: v1, latest
          registry: registry-url.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_USER_PASS }}
